version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: o2_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: openobserve_db
      POSTGRES_USER: openobserve_user
      POSTGRES_PASSWORD: openobserve_password
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - internal_net

  openobserve:
    image: public.ecr.aws/zinclabs/openobserve-enterprise:latest
    container_name: openobserve
    depends_on:
      - postgres
    environment:
      - ZO_DATA_DIR=/data
      - ZO_LOCAL_MODE=true
      - ZO_TELEMETRY=false
      - ZO_HTTP_ADDR=0.0.0.0:5080
      - ZO_JSON_LIMIT=209715200
      - ZO_PAYLOAD_LIMIT=209715200
      - ZO_META_STORE=postgres
      - ZO_META_POSTGRES_DSN=postgres://admin:openobserve_password@postgres:5432/openobserve_db
    volumes:
      - o2_data:/data
      - ./config/config.yaml:/etc/openobserve/config.yaml:ro
    restart: unless-stopped
    networks:
      - internal_net

  nginx:
    image: nginx:latest
    container_name: o2_nginx
    depends_on:
      - openobserve
    volumes:
      - ./nginx/openobserve.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - internal_net

volumes:
  o2_data:
  pg_data:

networks:
  internal_net:
    driver: bridge
